version: "1"

services:

  gescom-web-python:
      build: 
        context: ./consultorio/
        dockerfile: Dockerfile   
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
          - ./consultorio:/app
      ports:
          - "8000:8000"
